version: '3'
services:
  spark:
    #whether you want to build the docker image comment the "image" line and uncomment "build" line
    #build: docker
    image: neuw84/spark-zeppeling:latest
    ports:
     - "8080:8080"
     - "4040:4040"
    environment:
     - ZEPPELIN_JAVA_OPTS=-Dcassandra.hosts=cassandra
    volumes:
    - ./data:/usr/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook  
    links: 
    - cassandra
    depends_on: 
    - cassandra
  cassandra:
    image: cassandra:2    
    ports:
    - "9042:9042"
  nifi:
    image: mderela/apache-nifi:1.4.0
    ports:
    - "8090:8080"
    links:
    - mosquitto
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
     - zookeeper 
  mosquitto:
    image: vimagick/mosquitto
    ports:
    - "1883:1883"
    - "8070:8080"
    - "8883:8883"
    volumes:
    - ./mqtt/mosquitto.conf:/etc/mosquitto/mosquitto.conf
    - ./mqtt/pwfile:/etc/mosquitto/pwfile
    - ./mqtt:/var/lib/mosquitto
    restart: always


